import { NextRequest, NextResponse } from 'next/server';
export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';
import { sendBookingEmail } from '@/lib/mailer';

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const {
      to,
      subject = 'Your TripEase booking confirmation',
      html,
      text,
      booking,
    } = body || {};

    if (!to) {
      return NextResponse.json({ error: 'Missing recipient email' }, { status: 400 });
    }

    let emailHtml = html;
    let emailText = text;
    if (!emailHtml) {
      const title = booking?.title || booking?.name || 'Your booking';
      const details = JSON.stringify(booking ?? {}, null, 2);
      emailHtml = `
        <h2 style="font-family: Arial, sans-serif; color:#111">TripEase Booking Confirmation</h2>
        <p style="font-family: Arial, sans-serif; color:#333">Thank you for booking <strong>${title}</strong>.</p>
        <p style="font-family: Arial, sans-serif; color:#333">Here are your mock booking details:</p>
        <pre style="background:#f6f6f6; padding:12px; border-radius:8px; font-size:12px;">${details}</pre>
        <p style="font-family: Arial, sans-serif; color:#333">This is a demo confirmation generated by TripEase.</p>
      `;
      emailText = `TripEase Booking Confirmation\n\nThank you for booking ${title}.\n\nDetails (mock):\n${details}\n\nThis is a demo confirmation.`;
    }

    const result = await sendBookingEmail(to, subject, emailHtml, emailText);
    if (!result.success) {
      return NextResponse.json({ error: result.error || 'Failed to send email' }, { status: 500 });
    }

    return NextResponse.json({ ok: true, transport: result.transport, id: result.id, filePath: result.filePath });
  } catch (err: any) {
    return NextResponse.json({ error: err?.message || 'Unexpected error' }, { status: 500 });
  }
}
